[package]
name = "workshop"
version = "0.1.0"
authors = ["Andrew Martin <0andrewmartin0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
piston_window = "0.98.0"
